apiVersion: resource.k8s.io/v1alpha3
kind: DeviceClass
metadata:
  name: gpu-nvidia
spec:
  selectors:
  - cel:
      expression: 'device.driver == "nvidia.com/gpu"'
  config:
  - opaque:
      driver: nvidia.com/gpu
      parameters:
        apiVersion: gpu.nvidia.com/v1alpha1
        kind: GpuClaimParameters
        sharing:
          strategy: TimeSlicing
          timeSlicingConfig:
            interval: "1s"
            replicas: 4
---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  name: gpu-claim-template
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu-nvidia
        count: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dra-driver-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: v1
    kind: Config
    driverName: nvidia.com/gpu
    nodeSelector:
      kubernetes.io/arch: amd64
    resources:
      - name: gpu
        vendor: nvidia.com
        capacity: 8
        allocatable: 8
