kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  DynamicResourceAllocation: true
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            feature-gates: "DynamicResourceAllocation=true"
        controllerManager:
          extraArgs:
            feature-gates: "DynamicResourceAllocation=true"
        scheduler:
          extraArgs:
            feature-gates: "DynamicResourceAllocation=true"
  - role: worker

